Repository AY2425S1-CS2103T-W14-4/tp, pull requests merged in 2024-10, with the labels that each got.

#38 Add EventfulNUS UI Mockup
  docs/images/Ui.png
Labels: type.Task, priority.High

#36 Add use cases 1 to 4
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#37 Add use cases 5 to 7
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#39 Add all user stories to DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#40 Add some terms to the glossary of the DG
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#42 Add non-functional requirements to Developer Guide
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#50 Enhance find command
  docs/DeveloperGuide.md
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/PersonContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/PersonContainsKeywordsPredicateTest.java
Labels: type.Story, priority.High

#51 Add UniqueTagList as part of Json support
  bin/main/seedu/address/model/tag/UniqueTagList.class
  src/main/java/seedu/address/model/tag/UniqueTagList.java
Labels: priority.High

#45 Add support for loading the help message from a file
  docs/help/help.txt
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: priority.High

#56 Change UI display of events
  src/main/java/seedu/address/model/event/Event.java
  src/main/resources/view/DarkTheme.css
Labels: priority.Medium

#58 add feature to find by events
  src/main/java/seedu/address/model/person/PersonContainsKeywordsPredicate.java
Labels: priority.High

#61 Improve help page
  docs/help/help.txt
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/person/PersonContainsKeywordsPredicate.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/address/model/event/EventTest.java
  src/test/java/seedu/address/model/person/role/RoleTest.java
Labels: priority.Medium

#62 Fix UI bugs from HelpWindow
  docs/help/help.txt
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: type.Bug, severity.VeryLow

#66 Add more tests for code coverage
  src/test/java/seedu/address/commons/util/StringUtilTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/util/SampleDataUtilTest.java
Labels: priority.Low

#70 Update UI
  docs/help/help.txt
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
Labels: priority.Medium

#67 add second column for events
  src/main/java/seedu/address/AppParameters.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/ui/EventCard.java
  src/main/java/seedu/address/ui/EventListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/resources/view/EventListCard.fxml
  src/main/resources/view/EventListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/model/event/EventTest.java
  src/test/java/seedu/address/ui/EventCardTest.java
  src/test/java/seedu/address/ui/EventListPanelTest.java
Labels: type.Task, priority.High

#72 Create Event Feature
  README.md
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddEventCommand.java
  src/main/java/seedu/address/logic/parser/AddEventCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/EventName.java
  src/main/java/seedu/address/model/event/UniqueEventList.java
  src/main/java/seedu/address/model/event/exceptions/DuplicateEventException.java
  src/main/java/seedu/address/model/event/exceptions/EventNotFoundException.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/storage/JsonAdaptedEvent.java
  src/main/java/seedu/address/storage/JsonAdaptedRole.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/EventCard.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/MainWindow.fxml
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/event/EventTest.java
  src/test/java/seedu/address/testutil/EventBuilder.java
  src/test/java/seedu/address/ui/EventCardTest.java
  src/test/java/seedu/address/ui/EventListPanelTest.java
Labels: type.Task, priority.High

#81 Update help page and UG
  docs/UserGuide.md
  docs/help/help.txt
Labels: priority.High

#82 Rework UI
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/MainWindow.fxml
Labels: priority.High

#85 Improve UI theme
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/Extensions.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/Theme.css
Labels: priority.Medium, severity.VeryLow

#87 Update Ui UML class diagram
  .gitignore
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
  src/main/java/seedu/address/ui/EventListPanel.java
  src/test/java/seedu/address/model/event/EventTest.java
  src/test/java/seedu/address/ui/TestFxmlObject.java
Labels: type.Task, priority.High
