Repository AY2425S1-CS2103T-W14-4/tp, pull requests merged in 2024-11, with the labels that each got.

#97 Update DG
  docs/DeveloperGuide.md
Labels: priority.Medium

#90 Update ug
  docs/UserGuide.md
  src/main/resources/view/DarkTheme.css
Labels: priority.High

#88 Update events feature
  build.gradle
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EditEventCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddEventCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/Venue.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/PersonContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/person/role/athlete/Sport.java
  src/main/java/seedu/address/model/person/role/athlete/SportString.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedEvent.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/EventCard.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/EventListCard.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/Theme.css
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicateEventAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddEventCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditEventCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddEventCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/event/EventContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/event/EventTest.java
  src/test/java/seedu/address/model/event/UniqueEventListTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/util/SampleDataUtilTest.java
  src/test/java/seedu/address/storage/JsonAdaptedEventTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/EventBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#89 Implement event deletion
  src/main/java/seedu/address/logic/commands/DeleteEventCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteEventCommandParser.java
  src/test/java/seedu/address/logic/commands/DeleteEventCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteEventCommandParserTest.java
Labels: priority.High

#111 Add listevent command
  src/main/java/seedu/address/logic/commands/ListEventCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/commands/ListEventCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: type.Enhancement, priority.Medium

#115 Add event features to user guide
  docs/UserGuide.md
  src/main/java/seedu/eventfulnus/logic/Messages.java
  src/main/java/seedu/eventfulnus/logic/parser/AddEventCommandParser.java
Labels: priority.High

#116 Add text shortcuts
  docs/UserGuide.md
  src/main/java/seedu/eventfulnus/logic/Messages.java
  src/main/java/seedu/eventfulnus/logic/parser/ParserUtil.java
  src/main/java/seedu/eventfulnus/model/person/Email.java
Labels: priority.Medium

#192 Improvements to DG and UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.High

#199 Change sub-event to event and remove UC4
  docs/DeveloperGuide.md
Labels: type.Bug, severity.Medium

#200 Role uml
  docs/DeveloperGuide.md
  docs/diagrams/RoleClassDiagram.puml
  docs/images/RoleClassDiagram.png
  docs/img.png
Labels: severity.Low, type.DocumentationBug

#203 Add planned enhancements dg
  docs/DeveloperGuide.md
Labels: type.DocumentationBug
